# Generated by Django 5.0.6 on 2024-06-15 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VMType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VMInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vm_instance', to=settings.AUTH_USER_MODEL)),
                ('vm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.vmtype')),
            ],
        ),
    ]
